### ISSUE TITLE
Output of ank apply is flickering

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#250]
Assume an Ankaios manifest with an error inside like:

```
apiVersion: v0.1
workloads:
  invalidworkload:
    runtime: podman
    agent: agent_A
    runtimeConfig: |
      image: docker.io/busybox:latest
      commandOptions: ["--invalidoption"]
```

When this is applied using `ank apply` the output flickers and is hard to read for the user. In regular intervals a newline is added between the header and the table content. See

![flickering_ank_apply2](https://github.com/eclipse-ankaios/ankaios/assets/13716595/0c3e9fa5-1d7c-49e2-9a05-6c4ec5ebc302)

In addition the final output does not contain the cause anymore:

```
❯ ank apply invalidworkload.yaml
 WORKLOAD NAME     AGENT     RUNTIME     EXECUTION STATE           ADDITIONAL INFO

 invalidworkload   agent_A   podman      Pending(StartingFailed)   No more retries.

```

which makes it even harder for the user to determine the problem (here the invalid option).

## Current Behavior

When `ank apply` is called and the manifest contains an error a retry is executed and the output between the retries changes its position.

## Expected Behavior

The output should not change its position such that it is easier for the user the read it and determine the error source. In addition the final message and also `ank get workloads` should show the real error message and not `No more retries`.

## Steps to Reproduce

1. Install Ankaios with the setup script
2. `sudo systemctl start ank-server ank-agent`
3. ank apply invalidworkload.yml (see above for content).

## Context (Environment)

* Ankaios v0.3.0
* Podman 4.9.3

## Final result

The propability of flickering output was decreased by keeping the state `Pending(Starting)` with an additional info message signaling that retries are done (`Retry X of 20: <failure_cause>) are being executed. This prevents the previous behavior that the columns content are moved back and forward when switching quickly between `Pending(Starting)` and `Pending(StartingFailed)` during retries causing the table output to flicker. In addition, the table output layout was improved to handle long additional info messages with newlines in a table better. In the `ank apply` command the additional info column is truncated to the remaining terminal width and in the `ank get workloads` command the full additional info message is shown, but wrapped to the remaining terminal width. If the terminal is too small so that not even the header fits in one line, the default table is output with no truncating/wrapping at all to prevent strange output.

**Comment by krucod3** [comment]
We can try a no-wrap functionality which cuts the line according to the size of the terminal.
To enrich the "Pending(StartingFailed)   No more retries." with more information we can use transition function for states or we can use the information available. Maybe we also need an additional sub-state for the no-more-retries.

**Comment by inf17101** [comment]
> We can try a no-wrap functionality which cuts the line according to the size of the terminal. To enrich the "Pending(StartingFailed) No more retries." with more information we can use transition function for states or we can use the information available. Maybe we also need an additional sub-state for the no-more-retries.

The `tabled` crate does not support a no wrap option. However I search for alternatives.

**Comment by windsource** [comment]
Somehow we need to handle long lines, i.e. lines that are longer than the terminal width. I see two options:

1. Truncate the line
2. Break the line but keep the text in the current column

If we break a line and continue in another column then it looks ugly.

**Comment by inf17101** [comment]
> Somehow we need to handle long lines, i.e. lines that are longer than the terminal width. I see two options:
> 
> 1. Truncate the line
> 2. Break the line but keep the text in the current column
> 
> If we break a line and continue in another column then it looks ugly.

I have tested a truncating and a wrap of the additional info column and both functions require a maximum width as a number as an argument. You can use percentage values, but it didn't work with the column-specific setting (compiler error). In order to get the available remaining width of the terminal for the last column, a manual calculation is necessary. The terminal size can be easily obtained using an existing crate in our code base, but determining the size of the columns using the Tabled create Table object is rather cumbersome (string table output parsing) or the column size can only be determined inaccurately. All the manual workarounds in the code appear to be impractical and error-prone.  I have created an issue describing our problem: https://github.com/zhiburt/tabled/issues/407. I hope the authors suggest a solution or a workaround.

**Comment by inf17101** [comment]
I implemented the following approach:

1. When the user runs `ank apply ...`, the additional info column is truncated and suffixed by '...' according to the available terminal width.
![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/e6afaeda-7a6c-4d88-bfec-257652b782b6)
2. When the user runs 'ank get workloads', the additional info column shows the full detailed message, but the column is wrapped according the available terminal width.
![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/c8a62bae-9307-4fb4-a1a7-0e100e6798e3)

3. For both commands, if the terminal window is too small so that the header column names cannot be shown in a single line I output the default table and no wrap/truncate is done. This prevents ugly output like this:  
![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/ae1ddb7e-0c13-4bf2-b4b4-b1e8408c1446)
How it looks:
![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/f74216c7-5ea7-483c-8e3e-677a805057cd)

**Comment by inf17101** [comment]
PR was reviewed and merged.
