### ISSUE TITLE
Handle dependencies when reusing workloads 

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#261]
At startup, the Ankaios agent always tries to reuse workloads. 
When the agent starts and finds a workload that already exists (in Podman this would mean the container exists), it will reuse it and regard it as already started regardless of its state (could also be failed). As the workload is considered to be already started, the dependencies are not checked. 

This behavior leads to unwanted end results.

## Current Behavior
* if a workload has finished execution (with success or error):
  * if the machines gets restarted or Ankaios agent is restarted: workload gets reused, dependencies are ignored. If restartsPolicy is configure it will not be applied regardless of the dependencies.
  **In this use-case we would actually like that the workloads is started again while considering the dependencies.**
* if a workload is running:
  * Ankaios agent gets restarted (machine still runs): **workload is reused and is still running without being restarted which is the desired behavior**
  * Machine gets restarted (along with the agent). Depending on the app the behavior is different:
    * If the app exists properly when stopped, like nginx, the container is in state "exited" after the restart
    * If the app does not handle the SIGTERM, the container is in state "Created" after the restart:
    ![image](https://github.com/eclipse-ankaios/ankaios/assets/36224699/54feb421-d8cc-4d40-9161-73454d7f81e0)
    Ankaios sees the container as "pending(starting), created" and is stuck in this state:
    ![image](https://github.com/eclipse-ankaios/ankaios/assets/36224699/b12c06f0-0e82-4658-916f-4e00a11d1aef)
**In both cases the workload shall be started again considering the dependencies as it is currently not running**

## Expected Behavior

Running workloads shall be reused, all other workload shall be restarted.

## Steps to Reproduce
Try out one of the described above use-cases.

## Context (Environment)
Ankaios v0.3
Manjaro Linux

## Final result

**To be filled by the one closing the issue.**

**Comment by krucod3** [comment]
We would need to return the execution state from the runtime (get_reusable_workloads) and handle not running workload in the AgentManager.

**Comment by inf17101** [comment]
The restart might be delayed after agent restarts because the delete requested by the RuntimeManager runs in a separate task and might be still executed during the create of the workload runs. The create fails the first times because the container name is already in use. The WorkloadControlLoop repeats the creates through the implemented retry mechanism. At the end the create is successfully done, but maybe with delays sometimes. This is because the restart is represented by an update (delete +create) operation instead of a real bundle restart. This will be fixed in #260.

**Comment by inf17101** [comment]
@krucod3: With the introduced fix, the display of workload states is not exactly according to the defined Ankaios workload state transitions anymore, when the workload must wait for its dependencies.

The reason is that the workload states are set inside the delete call - `Stopping(RequestedAtRuntime)` and "`Removed`" afterwards. The workload is enqueued because of not ready dependencies and the workload state is set to `Pending(WaitingToStart)`. Because the delete and the enqueue operation is decoupled from each other and are running in a different task, the `Pending(WaitingToStart)` may be overwritten by the `Stopping(RequestedAtRuntime)` and then the workload is removed out of the workload state db because of the sent `Removed` afterwards. The workload is started correctly when its dependencies are met, it is only a display issue not a functional issue.

Possible fixes:

1. Changing the `RuntimeFacade` interface to introduce a flag to enable/disable sending of workload states within the delete call or introducing a separate method inside the interface. => this is not my favorite solution because it is not a very clean fix.
2. Doing a Resume + Update operation instead of the Delete + Create to make sure that the create is executed after the delete

2 is the slower but cleaner solution to fulfill the Ankaios workload state transitions correctly.

But both fixes are anyway temporary until #260 is implemented.

**Comment by inf17101** [comment]
Option 2 was tested by me and then we have the problem that the state checker may overwrite the workload state with the first workload state it reports. This cannot be fixed since we need the resume in option 2 because the update operation would do only a create if the workload does not exist inside the RuntimeManager workload map.

I have implemented and tested option 1. It works at least. However this is not a clean fix.

**Comment by inf17101** [comment]
@windsource : I think we need to put some notes about the new agent restart behavior into the user documentation. Do you want to have a separate chapter for that or extending the existing restart or inter-workload dependencies chapter?

**Comment by maturar** [comment]
I have tried following scenario:

* start the server and agents with the config `tests/resources/configs/create_workloads_with_dependencies_config.yaml`
* stop the server and agents without restarting the VM
* start the server and agents again.

I got following traces in the agent_B:

```
2024-05-14T08:28:26Z INFO  ank_agent::runtime_manager] Deleting existing workload 'filesystem_init'. It is created when its dependencies are fulfilled.
[2024-05-14T08:28:26Z INFO  ank_agent::runtime_connectors::runtime_facade] Deleting 'podman' workload 'filesystem_init' on agent 'agent_B'
[2024-05-14T08:28:26Z INFO  ank_agent::runtime_manager] Deleting existing workload 'storage_provider'. It is created when its dependencies are fulfilled.
[2024-05-14T08:28:26Z INFO  ank_agent::runtime_connectors::runtime_facade] Deleting 'podman' workload 'storage_provider' on agent 'agent_B'
[2024-05-14T08:28:26Z INFO  ank_agent::runtime_manager] Found '0' existing 'podman-kube' workload(s).
[2024-05-14T08:28:26Z INFO  ank_agent::runtime_connectors::runtime_facade] Creating 'podman' workload 'filesystem_init'.
[2024-05-14T08:28:26Z INFO  ank_agent::runtime_connectors::podman::podman_runtime] Podman has returned error 'Execution of command failed: Error: creating container storage: the container name "filesystem_init.32d96f044b7c5ec8cf77040e8e932bd4c5fd029c68100f956af92bb328beb7ad.agent_B" is already in use by a67481e7707e31a882bc825d951b0e26511e0e19dcb3862880aabf56cd08494f. You have to remove that container to be able to reuse that name: that name is already in use, or use --replace to instruct Podman to do so.
    ', deleting broken container.
[2024-05-14T08:28:26Z INFO  ank_agent::workload::workload_control_loop] Failed to create workload: 'filesystem_init': 'Execution of command failed: Error: creating container storage: the container name "filesystem_init.32d96f044b7c5ec8cf77040e8e932bd4c5fd029c68100f956af92bb328beb7ad.agent_B" is already in use by a67481e7707e31a882bc825d951b0e26511e0e19dcb3862880aabf56cd08494f. You have to remove that container to be able to reuse that name: that name is already in use, or use --replace to instruct Podman to do so.
    '
[2024-05-14T08:28:28Z INFO  ank_agent::runtime_connectors::runtime_facade] Creating 'podman' workload 'storage_provider'.
```

The info traces with the failure from Podman are new. It does not happen in main. Do you have any idea what is going on?

**Comment by inf17101** [comment]
> I have tried following scenario:
> 
> * start the server and agents with the config `tests/resources/configs/create_workloads_with_dependencies_config.yaml`
> * stop the server and agents without restarting the VM
> * start the server and agents again.
> 
> I got following traces in the agent_B:
> 
> ```
> 2024-05-14T08:28:26Z INFO  ank_agent::runtime_manager] Deleting existing workload 'filesystem_init'. It is created when its dependencies are fulfilled.
> [2024-05-14T08:28:26Z INFO  ank_agent::runtime_connectors::runtime_facade] Deleting 'podman' workload 'filesystem_init' on agent 'agent_B'
> [2024-05-14T08:28:26Z INFO  ank_agent::runtime_manager] Deleting existing workload 'storage_provider'. It is created when its dependencies are fulfilled.
> [2024-05-14T08:28:26Z INFO  ank_agent::runtime_connectors::runtime_facade] Deleting 'podman' workload 'storage_provider' on agent 'agent_B'
> [2024-05-14T08:28:26Z INFO  ank_agent::runtime_manager] Found '0' existing 'podman-kube' workload(s).
> [2024-05-14T08:28:26Z INFO  ank_agent::runtime_connectors::runtime_facade] Creating 'podman' workload 'filesystem_init'.
> [2024-05-14T08:28:26Z INFO  ank_agent::runtime_connectors::podman::podman_runtime] Podman has returned error 'Execution of command failed: Error: creating container storage: the container name "filesystem_init.32d96f044b7c5ec8cf77040e8e932bd4c5fd029c68100f956af92bb328beb7ad.agent_B" is already in use by a67481e7707e31a882bc825d951b0e26511e0e19dcb3862880aabf56cd08494f. You have to remove that container to be able to reuse that name: that name is already in use, or use --replace to instruct Podman to do so.
>     ', deleting broken container.
> [2024-05-14T08:28:26Z INFO  ank_agent::workload::workload_control_loop] Failed to create workload: 'filesystem_init': 'Execution of command failed: Error: creating container storage: the container name "filesystem_init.32d96f044b7c5ec8cf77040e8e932bd4c5fd029c68100f956af92bb328beb7ad.agent_B" is already in use by a67481e7707e31a882bc825d951b0e26511e0e19dcb3862880aabf56cd08494f. You have to remove that container to be able to reuse that name: that name is already in use, or use --replace to instruct Podman to do so.
>     '
> [2024-05-14T08:28:28Z INFO  ank_agent::runtime_connectors::runtime_facade] Creating 'podman' workload 'storage_provider'.
> ```
> 
> The info traces with the failure from Podman are new. It does not happen in main. Do you have any idea what is going on?

It is because of the new logic for resuming and restarting workloads on initial startup. Our restart is represented by an update operation (Delete + Create) with considering inter-workload dependenices.

**Comment by maturar** [comment]
It is a bit strange for me, that we have there info traces saying "Podman has returned error", but it is not big issue. We can keep it as it is.

**Comment by inf17101** [comment]
The fix was done by resuming only running workloads and replacing workloads having a different workload state with considering the inter-workload dependencies for the create part. The workload state issue is fixed by introducing a temporary flag to disable/enable the reporting of workload states inside the RuntimeFacade's delete operation.
