### ISSUE TITLE
Hanging unit tests

### ISSUE THREAD

**Issue by maturar** [eclipse-ankaios/ankaios#58]
## Current Behavior
Here are some hanging unit tests in the Ankaios. This causes the build (Github action) to run forever:
`
test workload_facade::tests::utest_workload_facade_update_error_on_old_workload_delete ... ok
`
`
test control_interface::reopen_file::tests::test_write_reopen has been running for over 60 seconds
`
This happened in this build job:
https://github.com/eclipse-ankaios/ankaios/actions/runs/6467848515/job/17558726061

Probably the same issue has happened here:
https://github.com/eclipse-ankaios/ankaios/actions/runs/6479530356/job/17593237097

## Expected Behavior
`cargo test` always finishes. Tests shall either go through or fail after a timeout.

## Steps to Reproduce
Run `cargo test`. The issue has been observed in this pull request for the first time: https://github.com/eclipse-ankaios/ankaios/pull/54

## Context (Environment)
Architecure: x86
OS: Linux VM (Virtual Box)

## Logs
https://github.com/eclipse-ankaios/ankaios/actions/runs/6467848515/job/17558726061
https://github.com/eclipse-ankaios/ankaios/actions/runs/6479530356/job/17593237097

## Final result

Issue fixed by syncing the read/write operations from/into the FIFO file between the reader and writer task properly.

**Comment by lingnoi** [comment]
The unit test hangs because of two tasks (reader from and writer into a FIFO file) are not synchronized properly when interacting with the FIFO file. When working with the FIFO file it is important to know that it has to be open at both ends simultaneously before you can proceed to do any input or output operations on it.

To solve this we need to ensure that both ends (the reading and writing end) of the FIFO file are open properly.
