### ISSUE TITLE
Optimize CI/CD steps

### ISSUE THREAD

**Issue by lingnoi** [eclipse-ankaios/ankaios#91]
## Description

Optimize execution time CI/CD steps by for instance, reusing builds from previous build steps, etc.

## Goals

All CI/CD steps is executed only once for example, build executable for running utests, stests only once.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] For CI/CD, ensure to run only steps for PR verification
- [x] For CI/CD, ensure not to run the same steps multiple times

**Comment by inf17101** [comment]
I have seen that sometimes the post actions are taking a lot of time, for example the rust cache, see here as an example run:
![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/1a936c83-7e6b-49ef-a401-9463f64fc596)

**Comment by krucod3** [comment]
For PRs we should only run per commit:
* Unit tests
* System tests (Robot tests)

On main all actions should run incl. deb packages.

**Comment by inf17101** [comment]
I think it would be also great to enable `cargo clippy` that does extra code checks to catch common mistakes and to avoid code smells. We shall make the CI/CD pipeline fail if clippy detects something.

**Comment by inf17101** [comment]
Like discussed with @krucod3: In addition, we shall mark long running system tests and run them only in a nightly pipeline run.

**Comment by inf17101** [comment]
For better readability and single-point-of-change, I wanted to extract the conditions to check if certain steps shall be skipped into a environment variable and check the value of the env variable each time where needed. Then we can assign a more expressive name what the check does.

According to the GH Actions docs is the env context available in steps and jobs, ... . But when inserting the `if:...` to check the env variable inside a job condition, a bug is there, saying that .env is not known in job: https://github.com/eclipse-ankaios/ankaios/actions/runs/9114018663

There are several issues opened: https://github.com/actions/runner/issues/2372

When inserting the env variable check into a step condition, then it works.

For that reason, I have to copy the conditional expressions to every step and job that shall be skipped otherwise it would be not consistent.

**Comment by inf17101** [comment]
We can also think about changing the structure of workflows a little bit to group things within workflows together that belong together.

For example:

.github/workflows:
```
pr_validation.yml
merge_validation.yml
release.yml
documentation.yml
```

Then the merge_validation.yml and the release.yml can reuse the pr_validation.yml workflow. But as long as we keep this rust-cache, we must initialize the cache in each separated job using the rust build artifacts, which is overhead.

I am currently testing a little bit if the cache is really time saving or just overhead for the project. But the free Github actions resources in the cloud are not delivering reliable measurement info.

**Comment by inf17101** [comment]
I have tested some different CI/CD setups and came to the following conclusion:

![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/a2482bf9-7ccf-4dd9-a684-5f12d1779a32)

Currently, our build job is using the rust-cache and does all the jobs sequentially. In Rust, different builds can benefit from previous ones, e.g. a cargo clippy can benefit from a previous cargo build or cargo test to run with less execution time.
However, in our project the main time consuming pipeline task is to run the system tests. Only the run without build takes approx. 2.5 min, and in future potentially more time because of more system tests.

This means if we put the system tests execution into a sequence of other steps (building unit tests before and cargo clippy and all that stuff...), then the execution times are summed up, because each step is executed one after the other. In addition, the rust-cache saves a few seconds for each build (approx. 9 - 15 seconds). However, the cache setup time is approx. 46 sec and if the cache content is changing a lot through the new build and also some old artifacts must be cleaned up the worst case is that cache cleanup takes ~4 minute in the pipeline. So, the cache is not efficient at the moment, maybe caused by our dependecy / own code relationship is as high so that the cache has some benefit in this project (like mentioned in the rust-cache docs https://github.com/Swatinem/rust-cache?tab=readme-ov-file#cache-effectiveness).

The key here is too use not sequential steps in one GH Actions job, but use the parallelization mechanism of jobs inside GH Actions workflows to speed up. Our pipeline runtime is mainly driven by the execution times of the system tests, so the system tests must run as its own job freed from previous build steps. The system tests requires only a debug build before. So those builds must be put together to be able to run the system tests. The rest of the other pipeline steps can be distributed into other GH Actions jobs and it does not matter if we download the dependencies here and repeat build steps, because it does not save a lot of time currently in the project. The cost to build everything new in each separated job is less compared to the long runner (system test).

Summary:

Before pipeline refactoring and using cache + sequential build steps inside one job: best case ~6.x minutes, worst case: ~11.x min whole pipeline run.

After pipeline refactoring and using parallization and no cache: best case: ~4.x minutes and worst case: time for debug build + system test run

**Comment by inf17101** [comment]
@krucod3: I reduced the time now from ~6.5 minutes to ~ 4 min, see detailed explanation in the comment above. After removing the cache and better splitting the pipeline steps for more parallelization, I am wondering if we shall enable all the pipeline checks again. All disabled pipeline steps like Code Coverage, Debian packages, ... has significant lower runtime than the system test execution step, therefore these builds do not degrade the overall runtime of the pipeline. Enabling them would only have some advantages but not disadvantages. I will now enabling them again because pipeline runtime is not affected through this, but more checks have more benefit. Please let me know if you want me to turn them off again.

**Comment by krucod3** [comment]
@inf17101, parallelizing the steps sounds like a good idea and indeed means we can enable more checks when they run beside the others 👍 
As for the smaller dev container, it would definitely be great to do it, but it is outside of the scope here so we will tackle it later.

**Comment by inf17101** [comment]
I added a user doc and a fix for the condition checking if long-runtime stests shall be skipped on pull request verification.
